# -*- coding: utf-8 -*-
"""Notas de revisao por folha do MF00965787 rev.1 (11-4400-PEL-0301)."""

CRIT, IMP, INFO, PEND = "CRITICO", "IMPORTANTE", "INFO", "PENDENCIA"

FOLHAS = [
 ("01", "CAPA", [
  dict(id="D2", p=CRIT, onde="Relacao de documentos",
       acao="Listar os documentos que passam a integrar o projeto",
       porque="NR-10 10.2.3/10.3.9 e EN-ITE-839 5.1 exigem unifilar, memorial descritivo e relatorio de validacao; a ETC 3.3 e a ATN (itens 11, 12 e 16) exigem databook, PIT e ART. Hoje o pacote so tem o esquema funcional.",
       como="Incluir na capa a lista: diagrama unifilar; memorial descritivo NR-10 10.3.9; memorial termico; estudo de curto-circuito, coordenacao e seletividade; ART; PIT; plano de pintura; lista de sobressalentes de 2 anos; manuais O&M em portugues; databook CQ-ITE-003.",
       ref="NR-10 10.2.3 e 10.3.9; EN-ITE-839 5.1; ETC MF00857651 3.3; ATN 11/12/16"),
  dict(id="D3", p=IMP, onde="Quadro de dados nominais",
       acao="Incluir quadro com os dados nominais do conjunto",
       porque="A NBR IEC 61439-1 exige que as caracteristicas nominais estejam declaradas no projeto e na placa; hoje nao ha nenhum quadro de dados no desenho.",
       como="Acrescentar quadro com Un 690 VCA 3F+PE 60 Hz; In do conjunto; Icu do disjuntor geral e Icw/Ipk do conjunto (do estudo); grau de protecao; forma construtiva 4b; tensao de comando 24 Vcc; esquema de aterramento por alta resistencia (2 a 5 A).",
       ref="NBR IEC 61439-1; ELE-NRM-0001 4.4 e 6.5.2"),
  dict(id="C11", p=CRIT, onde="Nota geral da capa",
       acao="Registrar a advertencia de multiplas fontes de alimentacao",
       porque="O painel recebe 690 V do CCM 11-4400-QSA-0003 e 220 V do painel 11-4400-PLT-0011-1 (DJ-84). Abrir apenas o disjuntor geral nao desenergiza o painel, o que expoe a manutencao a risco direto.",
       como="Nota na capa e placa na porta: PAINEL ALIMENTADO POR MAIS DE UMA FONTE, indicando as duas origens e os disjuntores de bloqueio. Repetir a advertencia nas folhas 05 e 09.",
       ref="NR-10 10.3.1 e 10.5.1; NR-12 12.11.3; EN-ITE-839 5.2 e 5.8"),
  dict(id="D1", p=IMP, onde="Carimbo e tabelas de revisao",
       acao="Uniformizar datas e emitir a proxima revisao como PA",
       porque="As tabelas internas trazem 26/09/2025 e 04/12/2025 e a tabela do cliente traz rev.1 em 02/03/26; a finalidade esta como PI (Para Informacao), que nao submete o documento a aprovacao formal.",
       como="Alinhar as datas das duas tabelas, descrever a revisao como REVISADO CONFORME RELATORIO DE CONFORMIDADE e emitir com finalidade PA - PARA APROVACAO.",
       ref="AraucoSucuriu Documents Standard rev.01; ATN 3"),
 ]),

 ("02", "INDICE", [
  dict(id="D4", p=CRIT, onde="Indice de folhas",
       acao="Criar a folha do diagrama unifilar",
       porque="A NR-10 10.2.3 obriga esquema unifilar com o sistema de aterramento e os dispositivos de protecao. O projeto tem apenas o esquema funcional/multifilar - o unifilar nao existe.",
       como="Nova folha com entrada, disjuntor geral, barramento, os quatro alimentadores, protecoes, secoes de cabo, PE e indicacao dos compartimentos (forma 4b). Inserir no indice e renumerar o total de folhas.",
       ref="NR-10 10.2.3; EN-ITE-839 5.1.1"),
  dict(id="D5", p=INFO, onde="Indice de folhas",
       acao="Prever folhas de sinalizacao e de reguas de bornes",
       porque="As placas de seguranca e a nova regua Z precisam de documento proprio para a fabricacao executar e para o databook comprovar.",
       como="Acrescentar uma folha com a tabela de placas de seguranca e plaquetas de tag, e revisar a folha 10 para as tres reguas (X forca, Y comando, Z fontes externas).",
       ref="EN-ITE-839 5.5.5 e 5.8; NR-12 12.12"),
 ]),

 ("03", "LEGENDA", [
  dict(id="C9", p=CRIT, onde="Quadro CORES DE SINALIZACAO",
       acao="Inverter: vermelho = LIGADO e verde = DESLIGADO",
       porque="A legenda declara verde=ligado e vermelho=desligado, o inverso do padrao do cliente. Ha ainda contradicao interna: a fiacao das folhas 06 a 08 usa o vermelho como FALHA e o amarelo como DESLIGADO, e o layout da folha 09 mostra uma terceira combinacao.",
       como="Fixar BRANCO = painel energizado, VERMELHO = carga ligada, VERDE = carga desligada e AMARELO = falha. Corrigir ao mesmo tempo a legenda, o comando (06), as ligacoes (07 e 08), o layout (09) e a lista de materiais (11).",
       ref="ELE-NRM-0008 3.2.2 e 4; NR-10 10.3.9"),
  dict(id="M3", p=IMP, onde="Legenda - novo quadro",
       acao="Incluir e aplicar o codigo de cores da fiacao",
       porque="A IEC 60204-1 13.2.4, adotada pela EN-ITE-839 5.4.2, define cor por funcao de circuito. Hoje o 24 Vcc esta em vermelho/preto (deveria ser azul) e o laranja, reservado a circuitos energizados por fonte externa, esta em sinais internos dos inversores.",
       como="Quadro na legenda com preto=forca CA/CC; vermelho=comando CA; azul escuro=comando CC; laranja=alimentado por fonte externa; azul claro=neutro; verde/amarelo=PE. Aplicar na lista de bornes. Confirmar o padrao com a Valmet antes de cabear.",
       ref="IEC 60204-1 13.2.4; EN-ITE-839 5.4.2; ELE-NRM-0010 8"),
  dict(id="M14a", p=INFO, onde="Letras de identificacao",
       acao="Completar as letras que faltam",
       porque="A legenda nao cobre componentes que ja aparecem no projeto ou que serao incluidos, o que prejudica a leitura em campo.",
       como="Acrescentar Z = borne de fonte externa; VT = ventilacao do painel; DR = dispositivo diferencial residual. Manter X e Y como forca e comando.",
       ref="EN-ITE-839 5.4.2"),
 ]),

 ("04", "ESQUEMA DE FORCA", [
  dict(id="C7", p=CRIT, onde="Q1 (MDW-C125-3) e Q2 a Q5 (MDW-C10-3)",
       acao="Substituir por dispositivos com Ue maior ou igual a 690 V",
       porque="A linha MDW e minidisjuntor conforme NBR NM/IEC 60898, com tensao maxima de emprego de 440 VCA e capacidade de interrupcao referida a 230/400 V. Em 690 V nao ha poder de corte, curva nem Ue declarados. E a nao conformidade mais grave do projeto.",
       como="Entrada com disjuntor em caixa moldada de Ue maior ou igual a 690 V e Icu compativel com o Icc do ponto. Nos ramais, dispensar os MDW e proteger por seccionadora-fusivel com fusiveis aR de 690 V conforme a tabela de coordenacao tipo 2 do fabricante do inversor, ou disjuntor-motor de 690 V.",
       ref="NBR IEC 60947-2; NBR IEC 61439-1; IEC 60947-4-1; ELE-NRM-0001 6.5.2"),
  dict(id="C8", p=CRIT, onde="F1.1 a F4.3 (FNH000-25K-A)",
       acao="Especificar fusivel aR com Un maior ou igual a 690 V",
       porque="A linha FNH...K-A e de 500 VCA, insuficiente para a rede de 690 V. Alem disso o fusivel aR protege o semicondutor e nao o cabo do ramal: com a retirada dos MDW e preciso deixar claro quem protege o circuito.",
       como="Substituir por fusivel ultrarrapido aR da linha NH de 690 V, com corrente conforme a tabela do fabricante para o inversor aplicado, e registrar a coordenacao tipo 2 no estudo do item C13.",
       ref="IEC 60269-4; IEC 60947-4-1; ELE-NRM-0001 6.5.2"),
  dict(id="C13", p=CRIT, onde="Todo o esquema de forca",
       acao="Emitir estudo de curto-circuito, coordenacao e seletividade",
       porque="Sem o Icc do ponto nao se declara Icu, nem Icw do conjunto, nem se comprova a coordenacao tipo 2. A ELE-NRM-0008 fixa suportabilidade minima de 15 kA e a NR-10 10.3.9 exige memorial com a compatibilidade das protecoes.",
       como="Obter o Icc na saida do CCM 11-4400-QSA-0003 (pendencia Q1), emitir o memorial de curto, coordenacao e seletividade e declarar Icw e Ipk do conjunto no desenho e na placa.",
       ref="NBR IEC 61439-1; IEC 60947-4-1; NR-10 10.3.9; ELE-NRM-0008 3.2"),
  dict(id="C1", p=CRIT, onde="Limites de compartimento",
       acao="Indicar no esquema a segregacao por unidade funcional",
       porque="O cliente exigiu categoria 4B, que corresponde a forma construtiva 4b da NBR IEC 61439-2 exigida pelo ELE-NRM-0001 6.5.2. O esquema precisa mostrar o que fica em cada compartimento para a fabricacao executar a segregacao.",
       como="Traco tracejado delimitando o compartimento de entrada e barramento, um compartimento por acionamento (seccionadora, fusiveis, inversor e respectivos bornes de saida) e o compartimento de comando. Compatibilizar com a folha 09.",
       ref="NBR IEC 61439-2; ELE-NRM-0001 6.5.2"),
  dict(id="C5", p=CRIT, onde="F1 a F4",
       acao="Prever manopla na porta com bloqueio em cada ramal",
       porque="Comentario do cliente e NR-12 12.11.3b: cada carga deve poder ser bloqueada individualmente. Hoje as seccionadoras sao internas, o que obriga a parar o sistema inteiro para intervir em um ventilador.",
       como="Seccionadora-fusivel com acionamento externo na porta, bloqueavel por cadeado, uma por acionamento. Com a segregacao 4b fica uma manopla por compartimento.",
       ref="NR-12 12.11.3b; EN-ITE-839 5.2.1"),
  dict(id="C2", p=CRIT, onde="Q1",
       acao="Disjuntor geral com manopla na porta e bloqueio",
       porque="Comentario do cliente; a EN-ITE-839 5.2.1 e o PRC-0001 item 6 exigem seccionamento geral bloqueavel e acessivel entre 0,6 e 1,9 m. Hoje o Q1 e interno e a porta abre com o painel energizado.",
       como="Mecanismo rotativo com manopla na porta bloqueavel por cadeado e intertravamento de porta (abertura somente com o disjuntor aberto), manopla preta ou cinza. Sinalizar o trecho entre a entrada de cabos e o disjuntor, que permanece energizado.",
       ref="NR-10 10.3.1; NR-12 12.11.3; EN-ITE-839 5.2.1; PRC-0001 6"),
  dict(id="M1", p=IMP, onde="PE dos inversores (4 mm2)",
       acao="Elevar o condutor de protecao para 10 mm2",
       porque="Inversores de frequencia produzem corrente de fuga superior a 10 mA; nesse caso as normas exigem PE de no minimo 10 mm2 em cobre ou condutor de protecao duplicado.",
       como="PE dedicado de 10 mm2 por acionamento ate a barra de terra e barra geral de 16 mm2. Declarar as secoes no unifilar e na lista de bornes.",
       ref="IEC 60204-1; IEC 61800-5-1; EN-ITE-839 5.5.8"),
  dict(id="C14", p=IMP, onde="Cabos de forca 35 mm2 e 4 mm2",
       acao="Declarar classe de isolacao 0,6/1 kV",
       porque="A rede de 690 V e aterrada por alta resistencia (2 a 5 A). Na primeira falta a terra as fases sas permanecem a 690 V contra a terra em regime, o que inviabiliza fio de 450/750 V.",
       como="Especificar toda a fiacao de forca e os cabos de saida em 0,6/1 kV, declarando a classe no desenho e na lista de materiais, e verificar Ui maior ou igual a 690 V nos componentes de forca.",
       ref="ELE-NRM-0001 4.4; NBR 5410; NBR IEC 61439-1"),
  dict(id="M9", p=IMP, onde="U1 a U4",
       acao="Nota de configuracao dos inversores para rede IT/HRG",
       porque="Em rede aterrada por alta resistencia, manter o filtro RFI/MOV ligado provoca a queima do filtro na primeira falta a terra da planta.",
       como="Nota de fabricacao e comissionamento para remover o jumper ou parafuso do filtro RFI conforme o manual do fabricante antes da energizacao, com registro no relatorio de ensaios.",
       ref="ELE-NRM-0001 4.4; manual do inversor"),
  dict(id="M18", p=IMP, onde="Q1 - 125 A",
       acao="Redimensionar o disjuntor geral",
       porque="A carga total instalada e da ordem de 40 A. Um dispositivo de 125 A nao protege o cabo de 35 mm2 e encarece o conjunto sem beneficio.",
       como="Redimensionar (da ordem de 63 A) de forma coerente com o cabo, a demanda e o resultado da coordenacao do item C13.",
       ref="NBR 5410 6.3; NBR IEC 61439-1"),
  dict(id="C6", p=IMP, onde="Nota geral da folha",
       acao="Registrar entrada de cabos somente pela parte inferior",
       porque="Comentario expresso do cliente na folha 09; a nota precisa constar tambem no esquema de forca para orientar roteamento e furacao.",
       como="Nota ENTRADA DE CABOS SOMENTE PELA PARTE INFERIOR DO PAINEL, com placas de fundo removiveis e prensa-cabos PG que preservem o grau IP, e teto sem furacao.",
       ref="Comentario do cliente; EN-ITE-839 5.4.3"),
 ]),

 ("05", "ESQUEMA DE FORCA - AUXILIARES", [
  dict(id="C11", p=CRIT, onde="Q6 e entrada de 220 V",
       acao="Tornar o seccionamento de 220 V bloqueavel e sinalizar as duas fontes",
       porque="O circuito de 220 V vem do painel 11-4400-PLT-0011-1 (DJ-84) e permanece vivo com o Q1 aberto, assim como os sinais de incendio e do DCS. A NR-12 12.7.5 e 12.11.3 exige dispositivo para isolar todas as fontes, com bloqueio.",
       como="Q6 com trava para cadeado ou seccionadora rotativa bloqueavel; placa na porta indicando as duas origens e os disjuntores de bloqueio; fiacao dos circuitos externos em laranja e segregada na regua Z.",
       ref="NR-12 12.7.5 e 12.11.3; NR-10 10.3.1; EN-ITE-839 5.2 e 5.8"),
  dict(id="M12", p=IMP, onde="G1 - fonte 24 Vcc de 1,25 A",
       acao="Recalcular o consumo e ampliar a fonte",
       porque="A fonte alimenta 13 sinaleiros LED, o contator K1, tres reles de interface e dois controladores com IHM touch e interface sem fio. A margem e praticamente nula e nao ha reserva para os itens que serao acrescentados.",
       como="Levantar o consumo real, adotar fonte de 2,5 A ou superior com pelo menos 20 por cento de reserva e proteger a saida.",
       ref="EN-ITE-839 5.5.6; boa pratica de projeto"),
  dict(id="M10", p=IMP, onde="Circuitos auxiliares",
       acao="Incluir os acessorios obrigatorios do painel",
       porque="A ELE-NRM-0008 item 4, aplicavel por forca do ELE-NRM-0001 3.1 sem restricao, lista acessorios minimos que nao constam do projeto.",
       como="Acrescentar tomada de servico 2P+T padrao brasileiro protegida por DR de 30 mA, luminaria LED interna com acionamento automatico, porta-documentos e plaqueta de identificacao do painel.",
       ref="ELE-NRM-0008 4; IEC 60204-1; EN-ITE-839 5.5.2"),
  dict(id="M6", p=IMP, onde="Ventilacao do painel (2 x 120 x 120)",
       acao="Dimensionar a climatizacao por memorial e compatibilizar com o IP",
       porque="Os quatro inversores e a fonte dissipam da ordem de 700 a 900 W. A EN-ITE-839 5.4.7 exige analise especifica de dissipacao e o conjunto de grelha com filtro comum nao sustenta o IP55 exigido pelo criterio de HVAC.",
       como="Emitir memorial termico para temperatura ambiente de projeto de 40 C, adotar kit de ventilacao filtrada com IP declarado (ou trocador de calor) comandado por termostato e recalcular apos a compartimentacao.",
       ref="EN-ITE-839 5.4.7; PRC-0001 6; Mill Site Conditions 2.1.1"),
  dict(id="M16", p=INFO, onde="Barramento de neutro (7 posicoes)",
       acao="Identificar o neutro como exclusivo do circuito de 220 V",
       porque="A rede de 690 V e 3F+PE, sem neutro distribuido. Um barramento identificado apenas como neutro induz erro de montagem e de manutencao.",
       como="Renomear para N-220 V, segregar fisicamente do PE e identificar a barra de terra como PE.",
       ref="NBR 5410; EN-ITE-839 5.3.1"),
  dict(id="Q2", p=PEND, onde="Origem das alimentacoes",
       acao="Confirmar se as origens sao de circuito essencial ou UPS",
       porque="A pressurizacao de escada e sistema de seguranca contra incendio: se o circuito de 220 V cair, os controladores param e o sistema nao pressuriza. A NT 13 e a NBR 14880 exigem suprimento garantido.",
       como="Consultar a Valmet sobre a origem do 690 V (barra normal ou de emergencia do QSA) e do 220 V (DJ-84) e, se nao forem essenciais, propor a transferencia para a barra de emergencia.",
       ref="NBR 14880; NT 13 CBMMS; ELE-NRM-0001 4.4 e 6.7"),
 ]),

 ("06", "ESQUEMA DE COMANDO", [
  dict(id="C9", p=CRIT, onde="H2 a H13",
       acao="Corrigir a funcao das cores dos sinaleiros",
       porque="A fiacao liga FALHA nos sinaleiros vermelhos (H3, H6, H9 e H12) e DESLIGADO nos amarelos (H4, H7, H10 e H13), contrariando a ELE-NRM-0008, a NR-10 e a propria legenda da folha 03.",
       como="Refazer as ligacoes para vermelho = carga ligada, verde = carga desligada, amarelo = falha e branco (H1) = painel energizado, atualizando legenda, layout e lista de materiais na mesma revisao.",
       ref="ELE-NRM-0008 3.2.2 e 4; NR-10 10.3.9"),
  dict(id="C12", p=CRIT, onde="Alarme de incendio (K2) e controladores",
       acao="Implementar a comutacao para o segundo estagio de pressurizacao",
       porque="Compromisso contratual da ATN (itens 38 e 63) e da propria proposta: operacao continua em 15 Pa e elevacao para 50 Pa com foco de incendio. Hoje o alarme geral apenas energiza K2 e repete o sinal ao DCS - nada altera o set point.",
       como="Levar o contato do alarme geral a uma entrada digital do controlador de pressao (recurso de set point comutavel declarado na proposta) ou implementar segunda referencia nas entradas digitais dos inversores. Documentar a filosofia: normal 15 Pa, alarme 50 Pa, fumaca na casa de maquinas = parada.",
       ref="ATN 38 e 63; proposta 803/2; NBR 14880; NT 13 CBMMS"),
  dict(id="M4", p=IMP, onde="Bornes de incendio, guarita e DCS",
       acao="Criar regua Z separada para as fontes externas",
       porque="A EN-ITE-839 5.5.5 exige terminais separados em grupos de forca, comando e comando de fontes externas. Hoje os sinais de fumaca, guarita e alarme estao na regua Y de comando e permanecem energizados com o painel seccionado.",
       como="Criar a regua Z exclusiva para incendio e DCS, com tampa e placa de advertencia; manter X para forca e Y para comando; bornes a no minimo 200 mm da base.",
       ref="EN-ITE-839 5.5.5; NR-10 10.3.3.1"),
  dict(id="M14b", p=IMP, onde="K3 (acionamento remoto)",
       acao="Definir o componente K3 ou renomea-lo",
       porque="K3 aparece no esquema de comando mas nao consta da lista de materiais da folha 11, o que impede a compra e a montagem.",
       como="Se for rele de interface, incluir na lista de materiais; se for apenas o contato seco vindo do DCS, renomear para borne ou identificacao de sinal e remeter a regua Z.",
       ref="NR-10 10.3.9; consistencia documental"),
  dict(id="M3", p=INFO, onde="Fiacao de comando",
       acao="Ajustar as cores da fiacao de comando",
       porque="O 24 Vcc esta em vermelho e preto quando deveria ser azul, e o laranja, reservado a circuitos energizados por fonte externa, esta sendo usado em sinais internos.",
       como="Comando CC em azul escuro e laranja reservado para incendio, DCS e o 220 V a jusante do Q6; refazer a coluna de cores da lista de bornes.",
       ref="IEC 60204-1 13.2.4; EN-ITE-839 5.4.2"),
 ]),

 ("07", "LIGACAO DE CONTROLADOR I", [
  dict(id="C3", p=CRIT, onde="U1 e U2",
       acao="Prever IHM remota na porta para cada inversor",
       porque="Comentario do cliente e ELE-NRM-0001 6.5.5: e exigida no minimo uma IHM por inversor, instalada na porta do compartimento. Hoje a IHM fica no corpo do inversor, dentro do painel fechado.",
       como="Kit de IHM remota com moldura de porta e cabo por inversor, identificado com o tag do motor correspondente, incluindo os quatro kits na lista de materiais.",
       ref="ELE-NRM-0001 6.5.5; comentario do cliente"),
  dict(id="C12", p=CRIT, onde="Controlador de pressao",
       acao="Prever a entrada digital de comutacao de set point",
       porque="Sem essa entrada nao existe o segundo estagio de pressurizacao exigido na ATN (itens 38 e 63).",
       como="Ligar o contato do alarme geral de incendio (K2, folha 06) a uma entrada digital do controlador e parametrizar 15 Pa em operacao normal e 50 Pa em alarme, registrando os parametros no memorial e no databook.",
       ref="ATN 38 e 63; proposta 803/2"),
  dict(id="M2", p=IMP, onde="Compartimentos dos inversores",
       acao="Prever placa de advertencia de tensao residual",
       porque="A EN-ITE-839 5.5.9 exige sinalizacao quando a tensao residual permanece acima de 60 V por mais de 5 s; o barramento CC dos inversores tipicamente exige cerca de 10 minutos de espera.",
       como="Placa em cada compartimento de acionamento com AGUARDE 10 MINUTOS APOS DESENERGIZAR - TENSAO RESIDUAL, incluida na lista de placas de seguranca.",
       ref="EN-ITE-839 5.5.9; IEC 60204-1"),
  dict(id="M8", p=IMP, onde="Inversores e controlador",
       acao="Declarar a tropicalizacao dos eletronicos",
       porque="O ELE-NRM-0001 6.5.5 e o AUT-NRM-0001 3.1 exigem verniz de protecao (conformal coating) e classificacao ISA S71.04 G3 para a atmosfera da fabrica de celulose.",
       como="Especificar na lista de materiais o inversor com placas envernizadas e confirmar protecao equivalente no controlador de pressao.",
       ref="ELE-NRM-0001 6.5.5; AUT-NRM-0001 3.1"),
  dict(id="C4", p=IMP, onde="Sinalizacoes",
       acao="Identificar cada sinalizacao pelo tag da carga",
       porque="Comentario do cliente e EN-ITE-839 5.4.2: os componentes devem ter a mesma identificacao do projeto. O layout usa MOTOR 01 a 04 em vez do tag real.",
       como="Plaquetas de acrilico gravadas e fixadas por rebite ou parafuso, nunca adesivo, com o tag completo 11-4412-VNT-294x-MT1 em cada sinaleiro, botao, IHM e manopla.",
       ref="NR-12 12.3.5d; EN-ITE-839 5.4.2; ELE-NRM-0008 3.2.1"),
  dict(id="M14c", p=INFO, onde="Identificacao do controlador",
       acao="Uniformizar a identificacao do controlador",
       porque="O bloco esta identificado como STG02 no esquema e como STG1 na lista de bornes da folha 10, e o componente nao consta da lista de materiais.",
       como="Adotar um unico tag, corrigir as duas folhas e incluir o controlador na lista de materiais com part number.",
       ref="Consistencia documental; NR-10 10.3.9"),
  dict(id="Q6", p=PEND, onde="Interface com o DCS",
       acao="Confirmar a lista de sinais definitiva com o DCS",
       porque="O criterio de HVAC (PRC-0001 item 5) lista sinais analogicos do CLP para o DCS, enquanto o projeto entrega apenas contatos secos. A saida do controlador e 0-10 V e exigiria conversao para 4-20 mA.",
       como="Consultar a automacao da Valmet: se for exigida a variavel analogica de pressao, prever conversor e borne na regua Z e revisar as folhas 07 e 08.",
       ref="PRC-0001 5; AUT-NRM-0001"),
 ]),

 ("08", "LIGACAO DE CONTROLADOR II", [
  dict(id="C9", p=CRIT, onde="H8 a H13",
       acao="Corrigir as cores dos sinaleiros dos motores 03 e 04",
       porque="Mesma inversao apontada na folha 06: falha ligada ao sinaleiro vermelho e desligado ao amarelo.",
       como="Vermelho = ligado, verde = desligado e amarelo = falha, corrigindo em conjunto com as folhas 03, 06, 09 e 11.",
       ref="ELE-NRM-0008 3.2.2 e 4; NR-10"),
  dict(id="C3", p=CRIT, onde="U3 e U4",
       acao="Prever IHM remota na porta",
       porque="Mesma exigencia da folha 07: comentario do cliente e ELE-NRM-0001 6.5.5.",
       como="Kit de IHM remota por inversor, identificado pelo tag do motor.",
       ref="ELE-NRM-0001 6.5.5"),
  dict(id="M14d", p=IMP, onde="Reles de interface K4 e K5",
       acao="Conferir os reles de interface na lista de materiais",
       porque="Os reles de sinalizacao ao DCS (falha do controlador e sistema em execucao) precisam estar declarados com quantidade e part number para a compra.",
       como="Revisar a lista de materiais da folha 11 incluindo todos os reles de interface e conferindo os tags usados nas folhas 06, 07 e 08.",
       ref="Consistencia documental"),
  dict(id="C4", p=IMP, onde="Sinalizacoes dos motores 03 e 04",
       acao="Identificar pelo tag da carga",
       porque="Comentario do cliente; mesma exigencia da folha 07.",
       como="Plaquetas com 11-4412-VNT-2943-MT1 e 11-4412-VNT-2944-MT1 nos respectivos sinaleiros.",
       ref="NR-12 12.3.5d; EN-ITE-839 5.4.2"),
 ]),

 ("09", "LAYOUT MECANICO", [
  dict(id="C1", p=CRIT, onde="Todo o painel - comentario do cliente",
       acao="Compartimentar o painel para a forma construtiva 4b",
       porque="Exigencia expressa do cliente (compartimentar painel para se adequar a categoria 4B) e criterio ELE-NRM-0001 6.5.2, que fixa forma 4b para conjuntos da rede de 690 V. O layout atual e monobloco, com barramento, quatro inversores, comando e bornes no mesmo volume.",
       como="Forma 4b significa barramento segregado das unidades funcionais e cada unidade funcional em compartimento proprio, incluindo os terminais de saida. Adotar involucro modular compartimentado ou kits de segregacao metalica com compartimento de entrada e barramento, quatro compartimentos de acionamento, compartimento de comando e reguas por unidade. Impacta dimensoes, dissipacao e custo: redesenhar antes de comprar o involucro e confirmar com a Valmet se aceitam segregacao interna em involucro unico ou esperam colunas tipo CCM.",
       ref="NBR IEC 61439-2; ELE-NRM-0001 6.5.2; comentario do cliente"),
  dict(id="C2", p=CRIT, onde="Porta - comentario do cliente",
       acao="Chave de manobra do disjuntor de entrada na porta, com bloqueio",
       porque="Comentario do cliente e EN-ITE-839 5.2.1: seccionadora geral com lock out, entre 0,6 e 1,9 m do piso, que nao secciona o PE e nao serve de liga e desliga de processo.",
       como="Mecanismo rotativo com manopla na porta bloqueavel por ate tres cadeados, com intertravamento de porta e liberacao por ferramenta para manutencao autorizada, manopla preta ou cinza.",
       ref="NR-12 12.11.3b; EN-ITE-839 5.2.1; PRC-0001 6"),
  dict(id="C3", p=CRIT, onde="Porta - comentario do cliente",
       acao="Instalar as IHM dos inversores na porta",
       porque="Comentario do cliente e ELE-NRM-0001 6.5.5, que exige uma IHM por inversor na porta do compartimento.",
       como="Quatro kits de IHM remota na porta, um por compartimento de acionamento, com plaqueta do tag do motor.",
       ref="ELE-NRM-0001 6.5.5; comentario do cliente"),
  dict(id="C4", p=CRIT, onde="Sinalizacoes da porta - comentario do cliente",
       acao="Identificar todas as sinalizacoes pelo tag das cargas",
       porque="Comentario do cliente; a NR-12 12.3.5d e a ELE-NRM-0008 3.2.1 exigem identificacao por plaqueta de acrilico rebitada ou parafusada.",
       como="Substituir MOTOR 01 a 04 pelos tags 11-4412-VNT-2941 a 2944-MT1 em cada sinaleiro, botao, IHM e manopla, e incluir a tabela de plaquetas no desenho.",
       ref="NR-12 12.3.5d; EN-ITE-839 5.4.2; ELE-NRM-0008 3.2.1"),
  dict(id="C5", p=CRIT, onde="Porta - comentario do cliente",
       acao="Bloqueio individual por carga com metodo mecanico na porta",
       porque="Comentario do cliente e NR-12 12.11.3b. Permite bloquear um ventilador para manutencao sem parar os demais, o que e essencial em um sistema com redundancia.",
       como="Uma manopla externa bloqueavel por cadeado por acionamento; com a forma 4b, uma manopla por compartimento.",
       ref="NR-12 12.11.3b; EN-ITE-839 5.2.1"),
  dict(id="C10", p=CRIT, onde="Involucro",
       acao="Declarar o grau de protecao e adequar a ventilacao",
       porque="O criterio de HVAC (PRC-0001 item 6) exige no minimo IP55 para paineis eletricos; o desenho nao declara IP e o conjunto de grelha com filtro comum nao sustenta esse grau.",
       como="Declarar o IP do conjunto no desenho e adotar kit de ventilacao filtrada com IP54 ou IP55 declarado, ou climatizacao, conforme o memorial termico. Se a Valmet aceitar IP42 por ser sala fechada, registrar a aceitacao por escrito.",
       ref="PRC-0001 6; NBR IEC 60529; EN-ITE-839 5.4.3; ELE-NRM-0008 3.2"),
  dict(id="C6", p=IMP, onde="Entrada de cabos - comentario do cliente",
       acao="Detalhar a entrada de cabos apenas pela parte inferior",
       porque="Comentario do cliente; o desenho nao declara o arranjo de entrada nem a preservacao do grau IP.",
       como="Placas de fundo removiveis e parafusadas com prensa-cabos PG, teto sem furacao e vedado, indicando a regiao de entrada no desenho.",
       ref="Comentario do cliente; EN-ITE-839 5.4.3"),
  dict(id="M5", p=IMP, onde="Partes vivas internas",
       acao="Prever espelho interno e coberturas sobre partes energizadas",
       porque="A ETC 3.2 exige protecao contra toque acidental e a EN-ITE-839 5.4.4 com a ELE-NRM-0008 3.2.1 preveem espelho interno em policarbonato de 5 mm com abertura para as manoplas.",
       como="Espelho interno e coberturas acrilicas sobre a chegada do geral, o barramento e os bornes de forca, incluidos na lista de materiais.",
       ref="ETC MF00857651 3.2; EN-ITE-839 5.4.4; ELE-NRM-0008 3.2.1"),
  dict(id="M7", p=IMP, onde="Espaco de reserva",
       acao="Prever reserva de circuitos e espaco fisico",
       porque="A NBR 5410 tabela 59, citada na EN-ITE-839 5.4.1, e a ELE-NRM-0008 exigem reserva minima; hoje ha apenas um circuito reserva em 220 V.",
       como="Prever espaco e infraestrutura para ao menos um alimentador de 690 V futuro e dois circuitos auxiliares, refletindo no barramento e no layout.",
       ref="NBR 5410 tabela 59; EN-ITE-839 5.4.1; ELE-NRM-0008 3.2.2"),
  dict(id="M11", p=IMP, onde="Sinalizacao de seguranca",
       acao="Incluir a tabela de placas de seguranca",
       porque="A EN-ITE-839 5.8 remete aos modelos da EN-ITE-774, a NR-10 anexo II exige placa de arco eletrico e a ETC 3.5 exige placa de identificacao conforme NR-12. Nada disso consta do desenho.",
       como="Tabela de placas com risco de choque e pessoal autorizado na porta, multiplas fontes, tensao residual nos compartimentos de acionamento, inicio e fim de circuito, placa de arco (zona de risco 0,2 m e controlada 0,7 m, distancia de trabalho 457 mm), placa NR-12 e placa diagramatica.",
       ref="EN-ITE-839 5.8 e 6; NR-10 anexo II; NR-12 12.12; ETC 3.5"),
  dict(id="M13", p=INFO, onde="Acabamento",
       acao="Declarar pintura e espessura de chapa",
       porque="A ELE-NRM-0008 3.2.1 e 3.2.3 fixa chapa minima 1,95 mm, base 2,7 mm, pintura cinza claro Munsell N 6,5 e placa de montagem laranja 2,5YR 6/14 conforme o padrao 10-0000-CIV-0002.",
       como="Declarar cor, esquema de pintura e espessuras no desenho e enviar o plano de pintura para aprovacao, conforme compromisso da ATN item 23.",
       ref="ELE-NRM-0008 3.2.1 e 3.2.3; 10-0000-CIV-0002-NRM; ATN 23"),
  dict(id="M14e", p=INFO, onde="Nota de canaletas",
       acao="Corrigir o erro de grafia na nota",
       porque="A nota traz CANALTERA em vez de CANALETA.",
       como="Corrigir o texto da nota na proxima emissao.",
       ref="Revisao editorial"),
 ]),

 ("10", "LISTA DE BORNES", [
  dict(id="M4", p=IMP, onde="Regua Y - bornes 5 a 10",
       acao="Transferir os sinais externos para uma regua Z",
       porque="Os bornes de fumaca, guarita e alarme estao na regua de comando, misturando circuitos alimentados por fonte externa com o 24 Vcc do painel. A EN-ITE-839 5.5.5 exige grupos separados e esses circuitos permanecem energizados com o painel seccionado.",
       como="Criar a regua Z para incendio e DCS com tampa e placa de advertencia, mantendo X para forca e Y para comando, e renumerar a lista e o esquema de comando.",
       ref="EN-ITE-839 5.5.5; NR-10 10.3.3.1"),
  dict(id="M1", p=IMP, onde="Bornes X4, X8, X12 e X16 (PE 4 mm2)",
       acao="Elevar o PE para 10 mm2",
       porque="A corrente de fuga dos inversores e superior a 10 mA, o que exige PE de no minimo 10 mm2.",
       como="Substituir por borne de terra de 10 mm2 por acionamento e ajustar as colunas de secao e cor da lista.",
       ref="IEC 60204-1; IEC 61800-5-1; EN-ITE-839 5.5.8"),
  dict(id="M15", p=INFO, onde="Bitola dos cabos de comando",
       acao="Uniformizar a bitola de comando",
       porque="A nota da folha 09 indica 0,75 mm2 enquanto a lista de bornes usa 1,0 e 1,5 mm2, divergencia que gera duvida na fabricacao.",
       como="Padronizar 1,0 mm2 como minimo geral de comando e corrigir a nota da folha 09.",
       ref="IEC 60204-1 tabela 5; EN-ITE-839 5.5.2"),
  dict(id="M7", p=IMP, onde="Todas as reguas",
       acao="Prever reserva de bornes",
       porque="A ELE-NRM-0008 exige ao menos 20 por cento de reserva e a lista atual nao preve bornes livres.",
       como="Acrescentar 20 por cento de bornes reserva em cada regua e indicar as posicoes livres.",
       ref="ELE-NRM-0008 3.2.2; NBR 5410 tabela 59"),
  dict(id="M14f", p=INFO, onde="Contagem de bornes",
       acao="Conferir as quantidades declaradas",
       porque="A lista de materiais declara 19 bornes X e 27 bornes Y, enquanto a lista de bornes usa 21 e 28 posicoes respectivamente.",
       como="Recontar apos a criacao da regua Z e da reserva e alinhar as duas folhas.",
       ref="Consistencia documental"),
  dict(id="EN1", p=INFO, onde="Posicao das reguas",
       acao="Posicionar os bornes a no minimo 200 mm da base",
       porque="Requisito da IEC 60204-1 adotado pela EN-ITE-839 5.5.5 para permitir conexao e manutencao com ergonomia.",
       como="Conferir a cota no layout mecanico da folha 09 e registrar no desenho.",
       ref="IEC 60204-1; EN-ITE-839 5.5.5"),
 ]),

 ("11", "LISTA DE MATERIAIS", [
  dict(id="C7", p=CRIT, onde="Q1 e Q2 a Q5 (linha MDW)",
       acao="Substituir pelos dispositivos de 690 V",
       porque="Consequencia direta do item C7 da folha 04: minidisjuntores de 440 V nao podem ser aplicados em 690 V.",
       como="Disjuntor em caixa moldada com Ue maior ou igual a 690 V na entrada e seccionadora-fusivel com manopla na porta nos ramais, incluindo os mecanismos de manopla e bloqueio como itens da lista.",
       ref="NBR IEC 60947-2; ELE-NRM-0001 6.5.2"),
  dict(id="C8", p=CRIT, onde="Fusiveis FNH000-25K-A",
       acao="Substituir por fusivel aR de 690 V",
       porque="A linha especificada e de 500 V, insuficiente para a rede de 690 V.",
       como="Fusivel ultrarrapido aR NH de 690 V com corrente conforme a tabela de coordenacao do fabricante do inversor.",
       ref="IEC 60269-4"),
  dict(id="M14g", p=IMP, onde="Diversos itens da lista",
       acao="Corrigir os erros de preenchimento",
       porque="A lista traz o part number 787-1702 da WAGO, que e a fonte de alimentacao, atribuido aos ventiladores de painel; a fonte G1 fica sem part number; K3 aparece no comando mas nao na lista; o controlador de pressao e a ventilacao VT1 nao constam; ha divergencia nas quantidades de bornes.",
       como="Revisar item a item corrigindo o part number da fonte e dos ventiladores, incluir K3 ou remove-lo do comando, incluir o controlador de pressao e o conjunto de ventilacao e acertar as quantidades de bornes.",
       ref="NR-10 10.3.9; consistencia documental"),
  dict(id="C3", p=IMP, onde="Acessorios dos inversores",
       acao="Incluir os quatro kits de IHM remota",
       porque="Exigencia do cliente e do ELE-NRM-0001 6.5.5, que pede uma IHM por inversor na porta.",
       como="Acrescentar quatro kits de IHM remota com moldura de porta e cabo, com o part number do fabricante.",
       ref="ELE-NRM-0001 6.5.5"),
  dict(id="M12", p=IMP, onde="G1 - fonte 24 Vcc",
       acao="Ampliar a fonte para 2,5 A ou mais",
       porque="A fonte de 1,25 A nao atende ao consumo com reserva.",
       como="Especificar fonte chaveada de 24 Vcc com 2,5 A ou superior e protecao de saida.",
       ref="EN-ITE-839 5.5.6"),
  dict(id="M10", p=IMP, onde="Acessorios do painel",
       acao="Incluir os acessorios obrigatorios",
       porque="A ELE-NRM-0008 item 4 exige acessorios que nao constam da lista.",
       como="Acrescentar tomada de servico 2P+T com DR de 30 mA, luminaria LED interna com acionamento automatico, porta-documentos, plaqueta de identificacao e espelho interno.",
       ref="ELE-NRM-0008 4; IEC 60204-1"),
  dict(id="M11", p=IMP, onde="Sinalizacao de seguranca",
       acao="Incluir o conjunto de placas de seguranca",
       porque="As placas exigidas pela EN-ITE-839 5.8, pela NR-10 (arco eletrico) e pela NR-12 (placa de identificacao) nao constam da lista.",
       como="Incluir o conjunto de placas conforme a tabela criada na folha 09, com material e quantidade.",
       ref="EN-ITE-839 5.8; NR-10 anexo II; NR-12 12.12"),
  dict(id="Q4", p=PEND, onde="Fabricantes",
       acao="Conferir os componentes contra a vendor list",
       porque="A ETC exige que protecoes, inversores e motores estejam na vendor list do cliente e a lista atual nao foi confrontada com esse documento.",
       como="Solicitar a vendor list a Valmet e ajustar fabricantes e part numbers antes da compra.",
       ref="ETC MF00857651 1 e 3.2; ATN 37"),
 ]),
]
